version: '3'
services:
  jaka-service:
    build:
       context: ..
       dockerfile: .devcontainer/Dockerfile
    image: yc-dlan/jaka_driver:ros2 
    container_name: jaka_driver_container
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./..:/home/yc-dlan/jaka_ws
      - /dev:/dev
      - /run/udev:/run/udev:ro
    network_mode: host
    pid: "host" # 添加 pid 命名空间共享
    ipc: "host" # 添加 ipc 命名空间共享    
    privileged: true
    stdin_open: true
    tty: true
    user: "yc-dlan" 
    # runtime: "nvidia"
    working_dir: "/home/yc-dlan/jaka_ws" # 指定默认工作目录